import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { PanelModule } from 'primeng/panel';

@Component({
  selector: 'app-feed',
  standalone: true,
  imports: [PanelModule, CommonModule],
  templateUrl: './feed.component.html',
  styleUrl: './feed.component.css',
})
export class FeedComponent {
  posts = [
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    }, {
      username: 'foofaji',
      userAvatar: 'assets/foofaji-avatar.jpg',
      time: '4d',
      imageUrl: '../../assets/Picture1.jpg',
      likes: 'j_u_b_a_i_r_7',
      caption: 'Waterfall dekh lo mitron! 😂💦',
    },
    // Add more posts...
  ];
}
